"""create counter table

Revision ID: 73874ab662d8
Revises: 
Create Date: 2022-01-12 10:33:27.231425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73874ab662d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('counter')
    # ### end Alembic commands ###
